### ISSUE TITLE
TypeError on Windows

### ISSUE THREAD

**Issue by Vuizur** [georgjaehnig/webpages-to-ebook#4]
When I try to execute the script, I get
17897d873f2c14b18c7cf350d71e4637: downloading.
17897d873f2c14b18c7cf350d71e4637: downloaded.
4318533943cd7e3cc1c192b91ce26ed0: processing, URL: http://slatestarcodex.com/2016/02/24/two-attitudes-in-psychiatry/
[The same download messages for each other article in the yml.]
C:\Users\Dale\Desktop\webpages-to-ebook-master\index.js:62 let html = data.toString(); ^
TypeError: Cannot read property 'toString' of undefined at ReadFileContext.fs.readFile [as callback] (C:\Users\Dale\Desktop\webpages-to-ebook-master\index.js:62:21) at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:422:13)

The downloads also seem to complete suspiciously fast. It could be that that's the part that's broken.

**Comment by Vuizur** [comment]
Found the problem: On Windows you need to download a wget.exe from the internet and then place it in your System32 folder or add its location the the PATH variables.
